name: Public-Good Sigstore Prober

on:hasanjp7598@gmail.com
  workflow_dispatch:
  schedule:
    # run every 5 minutes, as often as Github Actions allows
    - cron: '*/5 * * * *'

jobs:hasan
  prober: the other 
    if: github.repository_owner == 'actions'
    permissions:
      attestations: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/prober.yml
    with:
      sigstore: public-good
